[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"


baseURL = 'https://jonathan-peterson.com/'
languageCode = 'en-us'
title = 'Jonathan Peterson'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false


[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  writing = "/writing/:slug/"
  dj = "/dj/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing/"
    weight = 30
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 40
  [[menu.main]]
    identifier = "dj"
    name = "DJ"
    url = "/dj/"
    weight = 50
